spring:
  datasource:
    username: djzxcs
    password: abc@1234
    url: jdbc:mysql://10.10.8.101:3306/djzx_cs

  datasource-second:
    username: uam
    password: uam
    url: jdbc:mysql://10.10.8.101:3306/uamdb


mybatis:
  type-aliases-package: com.lvlivejp.multidb.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
